import { parseDate, parseNumber, parseString } from "~/utils/parsers.ts";

export const documentRowSchema = [
  parseString("Claim ID"),
  parseString("Subscriber ID"),
  parseNumber("Member Sequence"),
  parseString("Claim Status"),
  parseNumber("Billed"),
  parseNumber("Allowed"),
  parseNumber("Paid"),
  parseDate("Payment Status Date"),
  parseDate("Service Date"),
  parseDate("Received Date"),
  parseDate("Entry Date"),
  parseDate("Processed Date"),
  parseDate("Paid Date"),
  parseString("Payment Status"),
  parseString("Group Name"),
  parseString("Group ID"),
  parseString("Division Name"),
  parseString("Division ID"),
  parseString("Plan"),
  parseString("Plan ID"),
  parseString("Place of Service"),
  parseString("Claim Type"),
  parseString("Procedure Code"),
  parseString("Member Gender"),
  parseString("Provider ID"),
  parseString("Provider Name"),
];
